name: WakaTime status update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "1 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: avinal/Profile-Readme-WakaTime@v3.0
        with: 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: main
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          

      
